parameters:
#    miw_practica.example.class: Miw\PracticaBundle\Example

services:
#    miw_practica.example:
#        class: %miw_practica.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
